### ISSUE TITLE
Documentation for the Project

### ISSUE THREAD

**Issue by toxicmender** [Shashank9830/Boolean-CKT-Reducer#3]
The internal Documentation is brief, but a more detailed Documentation is required for further involvement of a broader set of developers.

**Comment by Shashank9830** [comment]
README file has been updated for now.
Developer documentation will be added to the source code itself in the form of comments at required places.

**Comment by Shashank9830** [comment]
The source code now documented.

> (check /src/boolean_ckt_reduce.cpp)

Developers can now pull the latest commit to view the changed source file.
